### ISSUE TITLE
Database assignments

### ISSUE THREAD

**Issue by emysliwietz** [emysliwietz/hardware_security#9]
Public and Private Keys, necessary certificates
- [ ] Reception Terminal
- [ ] Smart Card
- [ ] Auto

**Comment by AVanVeen** [comment]
Database assigns necessary data to all necessary parties

**Comment by MaJoEi** [comment]
Private key, ID, certificate

**Comment by AVanVeen** [comment]
Potential design decision: Make it so that we already have communication established. So that means reception terminal, smart card, and auto already have their own keys, id, and certificates. 
Only thing we gotta do when testing then is make sure we set this up correctly with a well established database.

**Comment by AVanVeen** [comment]
If we want to do this though (which I think is the preferred solution as it saves a ton of work), we should check with Erik if we are allowed to do this

**Comment by AVanVeen** [comment]
Sidenote, this cannot really be easily done without https://github.com/emysliwietz/hardware_security/issues/8
For efficiency, it's better to first have a simple running DB which will simplify everything.
